In [4]:
import numpy as np
import random
from numpy.random import randint
from random import random as rnd
from random import gauss, randrange

population_size=6
x_max=0.5
x_min=0
sub_str=5
chromosome_length=2*int(round(sub_str))

Max_Gen=50
Gen=0

while Gen<=Max_Gen:
    #Generation of population of solution at random
    pop=np.zeros((population_size,chromosome_length))
    for i in range(population_size):
        for j in range(i,chromosome_length):
            pop[i,j] = random.randint(0, 1)
    print('Randomly generated population:\n',pop)

    #Decoded value
    sub1=np.zeros((population_size,int(round(sub_str))))
    dec1=np.zeros((population_size,1))
    for i in range(len(pop)):
        sub1[i]=pop[i][4::-1]
        for j in range(len(sub1[i])):
            sub1[i,j]=sub1[i,j]*np.power(2,j)
    for i in range(len(sub1)):
        dec1[i]=np.sum(sub1[i])
    sub2=np.zeros((population_size,int(round(sub_str))))
    dec2=np.zeros((population_size,1))
    for i in range(len(pop)):
        sub2[i]=pop[i][10:4:-1]
        for j in range(len(sub2[i])):
            sub2[i,j]=sub2[i,j]*np.power(2,j)
    for i in range(len(sub2)):
        dec2[i]=np.sum(sub2[i])
    decoded=np.concatenate((dec1,dec2),axis=1)
    print('Decode values:\n',decoded)

    #Linear mapping
    real=np.zeros((population_size,2))
    for i in range(len(decoded)):
        for j in range(len(decoded[i])):
            real[i,j]=x_min+((x_max-x_min)/(2**(int(round(sub_str)))-1))*decoded[i,j]
    print('Real values:\n',real)

    #Fitness Evaluation
    x1=np.zeros((population_size,1))
    x2=np.zeros((population_size,1))
    fitness_val=np.zeros((population_size,1))
    fitness_fun = -(x1+x2-2*(x1**2)-x2**2+(x1*x2))
    for i in range(len(real)):
        x1[i]=real[i][0]
    for j in range(len(real)):
        x2[j]=real[j][1]
    fitness_val=-(x1+x2-2*(x1**2)-x2**2+(x1*x2))
    print('Fitness value:\n',fitness_val)
    print('Max Fitness value:\n',np.max(fitness_val))
    print('Average Fitness value:\n',np.average(fitness_val))

    #Expected count
    sum_fitness=np.zeros((1,1))
    avg_fitness=np.zeros((1,1))
    probability=np.zeros((population_size,1))
    expected=np.zeros((population_size,1))
    for i in range(len(sum_fitness)):
        sum_fitness=np.sum(fitness_val)
    probability=np.divide(fitness_val,sum_fitness)
    print('Probability from Roullete Wheel:\n',probability)
    for i in range(len(avg_fitness)):
        avg_fitness=np.average(fitness_val)
    expected=np.divide(fitness_val,avg_fitness)
    expected=expected.tolist()
    print('Expected count:\n',expected)

    #Actual count
    actual=np.round(expected)
    actual_list=actual.tolist()
    from nltk import flatten
    actual_list = flatten(actual_list)
    print('Actual count:\n',actual_list)

    #Mating pool
    pool = np.repeat(pop, actual_list, axis=0)
    pool_list=pool.tolist()
    print('Mating pool:\n',pool_list)

    #Parents
    import math
    Pc=0.9
    individuals=int(round(population_size*Pc))
    parents=random.sample(pool_list,individuals)
    print('Parents for crossover:\n',parents)

    #Crossover
    for i in range(0,len(parents),2):
        r1=int(random.uniform(0,4))
        r2=int(random.uniform(5,10))
        if i+1 >= len(parents):
            break
        (parents[i][r1:r2+1], parents[i+1][r1:r2+1]) = (parents[i+1][r1:r2+1], parents[i][r1:r2+1])
    children=parents
    print('Children solution:\n',children)

    #Mutation
    Pm=0.05
    mutate=[]
    for i in range(len(children)):
        for j in range(len(children[i])):
            r=random.uniform(0,1)
            if r>=Pm:
                if children[i][j]==0.0:
                    children[i][j]=1.0
                elif children[i][j]==1.0:
                    children[i][j]=0.0
                else:
                    pass
            else:
                pass
    print('Mutated solution:\n',children)

    #Decoded value
    mut1=np.zeros((len(pool_list),int(round(sub_str))))
    mut_dec1=np.zeros((len(pool_list),1))
    for i in range(len(children)):
        mut1[i]=children[i][4::-1]
        for j in range(len(mut1[i])):
            mut1[i,j]=mut1[i,j]*np.power(2,j)
    for i in range(len(mut1)):
        mut_dec1[i]=np.sum(mut1[i])
    mut2=np.zeros((len(pool_list),int(round(sub_str))))
    mut_dec2=np.zeros((len(pool_list),1))
    for i in range(len(children)):
        mut2[i]=children[i][10:4:-1]
        for j in range(len(mut2[i])):
            mut2[i,j]=mut2[i,j]*np.power(2,j)
    for i in range(len(mut2)):
        mut_dec2[i]=np.sum(mut2[i])
    mut_decoded=np.concatenate((mut_dec1,mut_dec2),axis=1)
    print('Mutated solution after decoding:\n',mut_decoded)

    #Linear mapping
    real=np.zeros((len(pool_list),2))
    for i in range(len(mut_decoded)):
        for j in range(len(mut_decoded[i])):
            real[i,j]=x_min+((x_max-x_min)/(2**(int(round(sub_str)))-1))*mut_decoded[i,j]
    print('Real values of mutated solution:\n',real)

    #Fitness Evaluation
    xmut1=np.zeros((len(pool_list),1))
    xmut2=np.zeros((len(pool_list),1))
    mutfitness_val=np.zeros((len(pool_list),1))
    mutfitness_fun = -(xmut1+xmut2-2*(xmut1**2)-xmut2**2+(xmut1*xmut2))
    for i in range(len(real)):
        xmut1[i]=real[i][0]
    for j in range(len(real)):
        xmut2[j]=real[j][1]
    mutfitness_val=-(xmut1+xmut2-2*(xmut1**2)-xmut2**2+(xmut1*xmut2))
    mutfitness_val
    print('Fitness of mutated solution:\n',mutfitness_val)
    print('Max fitness of mutated solution:\n',np.max(mutfitness_val))
    print('Avg fitness of mutated solution:\n',np.average(mutfitness_val))

    Gen=Gen+1
print('The minimum value of given equation after 50 generation is:\n',np.max(mutfitness_val))    

Randomly generated population:
 [[1. 0. 0. 1. 1. 0. 0. 1. 0. 0.]
 [0. 1. 1. 1. 1. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]]
Decode values:
 [[19.  4.]
 [15.  3.]
 [ 0. 29.]
 [ 1. 28.]
 [ 1.  3.]
 [ 0. 24.]]
Real values:
 [[0.30645161 0.06451613]
 [0.24193548 0.0483871 ]
 [0.         0.46774194]
 [0.01612903 0.4516129 ]
 [0.01612903 0.0483871 ]
 [0.         0.38709677]]
Fitness value:
 [[-0.1987513 ]
 [-0.18262227]
 [-0.24895942]
 [-0.27055151]
 [-0.06243496]
 [-0.23725286]]
Max Fitness value:
 -0.06243496357960458
Average Fitness value:
 -0.20009538674991326
Probability from Roullete Wheel:
 [[0.16554713]
 [0.15211268]
 [0.20736728]
 [0.22535211]
 [0.05200433]
 [0.19761647]]
Expected count:
 [[0.993282773564464], [0.9126760563380284], [1.2442036836403036], [1.3521126760563382], [0.3120260021668473], [1.1856988082340196]]
Actual count:
 [1.0, 1.0, 1.0, 1.0, 0.0, 1.0]
Mating pool:
 

 [[18.  0.]
 [26.  5.]
 [23.  1.]
 [31.  1.]
 [25. 22.]
 [ 0.  0.]]
Real values of mutated solution:
 [[0.29032258 0.        ]
 [0.41935484 0.08064516]
 [0.37096774 0.01612903]
 [0.5        0.01612903]
 [0.40322581 0.35483871]
 [0.         0.        ]]
Fitness of mutated solution:
 [[-0.12174818]
 [-0.17559834]
 [-0.11758585]
 [-0.0239334 ]
 [-0.45005203]
 [-0.        ]]
Max fitness of mutated solution:
 -0.0
Avg fitness of mutated solution:
 -0.14815296566077005
Randomly generated population:
 [[0. 0. 0. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]]
Decode values:
 [[ 3. 24.]
 [ 4.  6.]
 [ 0. 20.]
 [ 1. 17.]
 [ 1. 30.]
 [ 0. 10.]]
Real values:
 [[0.0483871  0.38709677]
 [0.06451613 0.09677419]
 [0.         0.32258065]
 [0.01612903 0.27419355]
 [0.01612903 0.48387097]
 [0.         0.16129032]]
Fitness value:
 [[-0.29968783]
 [-0.14984391]
 [-0.21

 [[1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0], [1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0], [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0], [1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0], [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]]
Mutated solution after decoding:
 [[31.  2.]
 [18. 17.]
 [ 6. 14.]
 [29. 23.]
 [18.  4.]
 [ 0.  0.]]
Real values of mutated solution:
 [[0.5        0.03225806]
 [0.29032258 0.27419355]
 [0.09677419 0.22580645]
 [0.46774194 0.37096774]
 [0.29032258 0.06451613]
 [0.         0.        ]]
Fitness of mutated solution:
 [[-0.04734651]
 [-0.4003642 ]
 [-0.27471384]
 [-0.43704475]
 [-0.20083247]
 [-0.        ]]
Max fitness of mutated solution:
 -0.0
Avg fitness of mutated solution:
 -0.22671696149843912
Randomly generated population:
 [[1. 0. 1. 0. 0. 0. 0. 0. 1. 1.]
 [0. 1. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 1. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
Decode