In [1]:
import numpy as np
import random
from numpy.random import randint
from random import random as rnd
from random import gauss, randrange

population_size=6
x_max=0.5
x_min=0
sub_str=5
chromosome_length=2*int(round(sub_str))

Max_Gen=50
Gen=0

#Generation of population of solution at random
pop=np.zeros((population_size,chromosome_length))
for i in range(population_size):
    for j in range(i,chromosome_length):
        pop[i,j] = random.randint(0, 1)
print('Randomly generated population:\n',pop)

while Gen<=Max_Gen:
    #Decoded value
    sub1=np.zeros((population_size,int(round(sub_str))))
    dec1=np.zeros((population_size,1))
    for i in range(len(pop)):
        sub1[i]=pop[i][4::-1]
        for j in range(len(sub1[i])):
            sub1[i,j]=sub1[i,j]*np.power(2,j)
    for i in range(len(sub1)):
        dec1[i]=np.sum(sub1[i])
    sub2=np.zeros((population_size,int(round(sub_str))))
    dec2=np.zeros((population_size,1))
    for i in range(len(pop)):
        sub2[i]=pop[i][10:4:-1]
        for j in range(len(sub2[i])):
            sub2[i,j]=sub2[i,j]*np.power(2,j)
    for i in range(len(sub2)):
        dec2[i]=np.sum(sub2[i])
    decoded=np.concatenate((dec1,dec2),axis=1)
    print('Decode values:\n',decoded)

    #Linear mapping
    real=np.zeros((population_size,2))
    for i in range(len(decoded)):
        for j in range(len(decoded[i])):
            real[i,j]=x_min+((x_max-x_min)/(2**(int(round(sub_str)))-1))*decoded[i,j]
    print('Real values:\n',real)

    #Fitness Evaluation
    x1=np.zeros((population_size,1))
    x2=np.zeros((population_size,1))
    fitness_val=np.zeros((population_size,1))
    fitness_fun = -(x1+x2-2*(x1**2)-x2**2+(x1*x2))
    for i in range(len(real)):
        x1[i]=real[i][0]
    for j in range(len(real)):
        x2[j]=real[j][1]
    fitness_val=-(x1+x2-2*(x1**2)-x2**2+(x1*x2))
    print('Fitness value:\n',fitness_val)
    print('Max Fitness value:\n',np.max(fitness_val))
    print('Average Fitness value:\n',np.average(fitness_val))

    #Expected count
    sum_fitness=np.zeros((1,1))
    avg_fitness=np.zeros((1,1))
    probability=np.zeros((population_size,1))
    expected=np.zeros((population_size,1))
    for i in range(len(sum_fitness)):
        sum_fitness=np.sum(fitness_val)
    probability=np.divide(fitness_val,sum_fitness)
    print('Probability from Roullete Wheel:\n',probability)
    for i in range(len(avg_fitness)):
        avg_fitness=np.average(fitness_val)
    expected=np.divide(fitness_val,avg_fitness)
    expected=expected.tolist()
    print('Expected count:\n',expected)

    #Actual count
    actual=np.round(expected)
    actual_list=actual.tolist()
    from nltk import flatten
    actual_list = flatten(actual_list)
    print('Actual count:\n',actual_list)
  
    #Mating pool
    pool = np.repeat(pop, actual_list, axis=0)
    pool_list=pool.tolist()
    print('Mating pool:\n',pool_list)

    #Parents
    import math
    Pc=0.9
    individuals=int(round(population_size*Pc))
    parents=random.sample(pool_list,individuals)
    print('Parents for crossover:\n',parents)

    #Crossover
    for i in range(0,len(parents),2):
        r1=int(random.uniform(0,4))
        r2=int(random.uniform(5,10))
        if i+1 >= len(parents):
            break
        (parents[i][r1:r2+1], parents[i+1][r1:r2+1]) = (parents[i+1][r1:r2+1], parents[i][r1:r2+1])
    children=parents
    print('Children solution:\n',children)

    #Mutation
    Pm=0.05
    for i in range(len(children)):
        for j in range(len(children[i])):
            r=random.uniform(0,1)
            if r>=Pm:
                if children[i][j]==0.0:
                    children[i][j]=1.0
                elif children[i][j]==1.0:
                    children[i][j]=0.0
                else:
                    pass
            else:
                pass
    print('Mutated solution:\n',children)

    pop = np.array(children)
    add_row = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
    pop = np.vstack((pop,add_row)) 
    
    #Decoded value
    mut1=np.zeros((len(pool_list),int(round(sub_str))))
    mut_dec1=np.zeros((len(pool_list),1))
    for i in range(len(children)):
        mut1[i]=children[i][4::-1]
        for j in range(len(mut1[i])):
            mut1[i,j]=mut1[i,j]*np.power(2,j)
    for i in range(len(mut1)):
        mut_dec1[i]=np.sum(mut1[i])
    mut2=np.zeros((len(pool_list),int(round(sub_str))))
    mut_dec2=np.zeros((len(pool_list),1))
    for i in range(len(children)):
        mut2[i]=children[i][10:4:-1]
        for j in range(len(mut2[i])):
            mut2[i,j]=mut2[i,j]*np.power(2,j)
    for i in range(len(mut2)):
        mut_dec2[i]=np.sum(mut2[i])
    mut_decoded=np.concatenate((mut_dec1,mut_dec2),axis=1)
    print('Mutated solution after decoding:\n',mut_decoded)

    #Linear mapping
    real=np.zeros((len(pool_list),2))
    for i in range(len(mut_decoded)):
        for j in range(len(mut_decoded[i])):
            real[i,j]=x_min+((x_max-x_min)/(2**(int(round(sub_str)))-1))*mut_decoded[i,j]
    print('Real values of mutated solution:\n',real)

    #Fitness Evaluation
    xmut1=np.zeros((len(pool_list),1))
    xmut2=np.zeros((len(pool_list),1))
    mutfitness_val=np.zeros((len(pool_list),1))
    mutfitness_fun = -(xmut1+xmut2-2*(xmut1**2)-xmut2**2+(xmut1*xmut2))
    for i in range(len(real)):
        xmut1[i]=real[i][0]
    for j in range(len(real)):
        xmut2[j]=real[j][1]
    mutfitness_val=-(xmut1+xmut2-2*(xmut1**2)-xmut2**2+(xmut1*xmut2))
    mutfitness_val
    print('Fitness of mutated solution:\n',mutfitness_val)
    print('Max fitness of mutated solution:\n',np.max(mutfitness_val))
    print('Avg fitness of mutated solution:\n',np.average(mutfitness_val))

    Gen=Gen+1
print('The minimum value of given equation after 50 generation is:\n',np.max(mutfitness_val))    

Randomly generated population:
 [[1. 1. 1. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 1. 1. 1.]
 [0. 0. 1. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 1.]]
Decode values:
 [[29. 28.]
 [ 6.  7.]
 [ 4. 28.]
 [ 3. 24.]
 [ 0. 26.]
 [ 0.  9.]]
Real values:
 [[0.46774194 0.4516129 ]
 [0.09677419 0.11290323]
 [0.06451613 0.4516129 ]
 [0.0483871  0.38709677]
 [0.         0.41935484]
 [0.         0.14516129]]
Fitness value:
 [[-0.48907388]
 [-0.18912591]
 [-0.33298647]
 [-0.29968783]
 [-0.24349636]
 [-0.12408949]]
Max Fitness value:
 -0.12408949011446409
Average Fitness value:
 -0.2797433229275061
Probability from Roullete Wheel:
 [[0.29138252]
 [0.11267824]
 [0.1983881 ]
 [0.17854929]
 [0.1450713 ]
 [0.07393056]]
Expected count:
 [[1.7482951022938624], [0.6760694358338499], [1.1903285802851828], [1.0712957222566646], [0.8704277743335399], [0.4435833849969001]]
Actual count:
 [2.0, 1.0, 1.0, 1.0, 1.0, 0.0]
Mating pool:
 

 [[10.  0.]
 [ 2. 10.]
 [ 8. 21.]
 [ 6.  2.]
 [ 7. 14.]
 [ 0.  0.]]
Real values of mutated solution:
 [[0.16129032 0.        ]
 [0.03225806 0.16129032]
 [0.12903226 0.33870968]
 [0.09677419 0.03225806]
 [0.11290323 0.22580645]
 [0.         0.        ]]
Fitness of mutated solution:
 [[-0.10926119]
 [-0.17065557]
 [-0.36342352]
 [-0.11238293]
 [-0.28772112]
 [-0.        ]]
Max fitness of mutated solution:
 -0.0
Avg fitness of mutated solution:
 -0.17390738813735693
Decode values:
 [[10.  0.]
 [ 2. 10.]
 [ 8. 21.]
 [ 6.  2.]
 [ 7. 14.]
 [ 0.  0.]]
Real values:
 [[0.16129032 0.        ]
 [0.03225806 0.16129032]
 [0.12903226 0.33870968]
 [0.09677419 0.03225806]
 [0.11290323 0.22580645]
 [0.         0.        ]]
Fitness value:
 [[-0.10926119]
 [-0.17065557]
 [-0.36342352]
 [-0.11238293]
 [-0.28772112]
 [-0.        ]]
Max Fitness value:
 -0.0
Average Fitness value:
 -0.17390738813735693
Probability from Roullete Wheel:
 [[0.10471204]
 [0.16355024]
 [0.3482922 ]
 [0.10770381]
 [0.27574171]
 [0

 [2.0, 1.0, 1.0, 1.0, 1.0, 0.0]
Mating pool:
 [[0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0], [0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0], [0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0]]
Parents for crossover:
 [[0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0], [0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0]]
Children solution:
 [[0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0], [0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0]]
Mutated solution:
 [[1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0], [1.